DROP TABLE IF EXISTS #T
CREATE TABLE #T (col nvarchar(MAX))

BULK INSERT #T FROM 'C:\Users\fredr\Documents\AOC22\01\input.txt'
   WITH (  
      ROWTERMINATOR = '0x0a0a'  
		);  

DROP TABLE IF EXISTS #T1
SELECT 
	ROW_NUMBER() OVER (ORDER BY RAND()) ELF
	,col 
INTO #T1
FROM #T 

DROP TABLE IF EXISTS #T2
SELECT SUM(CAST(Value AS INT)) Calories, ROW_NUMBER() OVER ( ORDER BY SUM(CAST(Value AS INT)) DESC) RN   
INTO #T2
FROM #T1
	CROSS APPLY STRING_SPLIT(REPLACE(col,CHAR(10),'|'),'|')
GROUP BY ELF
ORDER BY SUM(CAST(Value AS INT)) DESC

SELECT 
SUM(IIF(RN=1,Calories,null)) [Top Elf]
,SUM(Calories) [Top 3 Elfs]
FROM #T2
WHERE RN<4
