DROP TABLE IF EXISTS #MVSTEST
SELECT * INTO #MVSTEST FROM (
--,MVSTEST AS (
SELECT 'move 1 from 2 to 1'		col1 UNION ALL
SELECT 'move 3 from 1 to 3'		col1 UNION ALL
SELECT 'move 2 from 2 to 1'		col1 UNION ALL
SELECT 'move 1 from 1 to 2'		col1
) X

DROP TABLE IF EXISTS #data
SELECT 
ROW_NUMBER() OVER ( ORDER BY (SELECT 1) ) RN
,CAST(SUBSTRING(col1, CHARINDEX('from ',col1)+5, 2) AS int) src
,CAST(SUBSTRING(col1, CHARINDEX('to ',col1)+2, 2) AS int) dst
,CAST(SUBSTRING(col1, CHARINDEX('move ',col1)+5, CHARINDEX(' from',col1)-5) AS int) qty
INTO #data
FROM #MVS

DECLARE @STRT TABLE(
    ID INT NOT NULL,
    ORD varchar(30) NULL
)
;WITH STRT AS (
SELECT 1 as ID,  'RSLFQ'	as ORD UNION ALL
SELECT 2 as ID,  'NZQGPT'	as ORD UNION ALL
SELECT 3 as ID,  'SMQB'		as ORD UNION ALL
SELECT 4 as ID,  'TGZJHCBQ'	as ORD UNION ALL
SELECT 5 as ID,  'PHMBNFS'	as ORD UNION ALL
SELECT 6 as ID,  'PCQNSLVG'	as ORD UNION ALL
SELECT 7 as ID,  'WCF'		as ORD UNION ALL
SELECT 8 as ID,  'QHGZWVPM'	as ORD UNION ALL
SELECT 9 as ID,  'GZDLCNR'	as ORD
)

INSERT INTO @STRT SELECT * FROM STRT

DECLARE @RN INT , @RNMAX INT, @src INT, @dst INT, @qty INT
SELECT @RN = MIN(RN) , @RNMAX = MAX(RN) 
FROM #data

WHILE(@RN IS NOT NULL AND @RN <= @RNMAX)
BEGIN
   SELECT @src = src, @dst = dst, @qty = qty FROM #data WHERE RN = @RN
   UPDATE @STRT
   SET ORD = (SELECT t.ORD+REVERSE(RIGHT((SELECT t.ORD FROM @STRT t WHERE t.ID = @src),@qty)) ORD FROM @STRT t WHERE t.ID = @dst)
   WHERE ID = @dst
   UPDATE @STRT
   SET ORD = (SELECT LEFT(t.ORD, LEN(t.ORD)-@qty) FROM @STRT t WHERE t.ID = @src)
   WHERE ID = @src
   SET @RN = @RN   + 1        
END

SELECT * FROM @STRT