DECLARE @BulkColumn VARCHAR(max)
SELECT @BulkColumn = REPLACE(BulkColumn, NCHAR(10),'|') FROM OPENROWSET (BULK 'C:\Users\fredr\Documents\AOC22\10\input.txt', SINGLE_CLOB) I

;WITH BASE AS (
SELECT ROW_NUMBER() OVER( ORDER BY (SELECT 1)) RN, value Operation FROM STRING_SPLIT (@BulkColumn,'|'))

,CYCLES AS (
SELECT 
	ROW_NUMBER() OVER ( ORDER BY RN, PL )-1 Cycle
	,(1+(ROW_NUMBER() OVER ( ORDER BY RN, PL )-2) % 40)-1 Pos
	,(ROW_NUMBER() OVER ( ORDER BY RN, PL )-2) / 40 Grp
	, SUM(PL) OVER ( ORDER BY RN, PL ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) Cum 
	FROM (
	SELECT B.RN, null as PL FROM BASE B WHERE LEFT(B.Operation,1)='A' AND B.Operation <> ''
	UNION ALL
	SELECT B.RN, NULLIF(TRY_CAST(RIGHT(B.Operation, LEN(B.Operation)-4) AS INT),0) PL FROM BASE B WHERE B.Operation <> ''
	UNION 
	SELECT 0, 1
) X
) 

SELECT CAST(SUM((Cycle)*Cum) AS VARCHAR(20)) Amnt FROM CYCLES WHERE Cycle IN (20, 60, 100, 140, 180, 220)
UNION ALL
SELECT STRING_AGG(IIF(Cum >= Pos-1 AND Cum <= Pos+1, 'X','_'),'') FROM CYCLES WHERE Cycle >= 1 GROUP BY GRP





